# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.edu1MSP:
    container_name: peer0.edu1MSP
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.edu1MSP
      - CORE_PEER_ADDRESS=peer0.edu1MSP:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.edu1MSP:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.edu1MSP:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.edu1MSP:7051
      - CORE_PEER_LOCALMSPID=edu1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/edu1MSP/peers/peer0.edu1MSP/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/edu1MSP/peers/peer0.edu1MSP/tls:/etc/hyperledger/fabric/tls
        - peer0.edu1MSP:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.edu1MSP:
    container_name: peer1.edu1MSP
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.edu1MSP
      - CORE_PEER_ADDRESS=peer1.edu1MSP:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.edu1MSP:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.edu1MSP:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.edu1MSP:7051
      - CORE_PEER_LOCALMSPID=edu1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/edu1MSP/peers/peer1.edu1MSP/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/edu1MSP/peers/peer1.edu1MSP/tls:/etc/hyperledger/fabric/tls
        - peer1.edu1MSP:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.edu2MSP:
    container_name: peer0.edu2MSP
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.edu2MSP
      - CORE_PEER_ADDRESS=peer0.edu2MSP:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.edu2MSP:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.edu2MSP:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.edu2MSP:10051
      - CORE_PEER_LOCALMSPID=edu2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/edu2MSP/peers/peer0.edu2MSP/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/edu2MSP/peers/peer0.edu2MSP/tls:/etc/hyperledger/fabric/tls
        - peer0.edu2MSP:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.edu2MSP:
    container_name: peer1.edu2MSP
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.edu2MSP
      - CORE_PEER_ADDRESS=peer1.edu2MSP:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.edu2MSP:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.edu2MSP:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.edu2MSP:9051
      - CORE_PEER_LOCALMSPID=edu2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/edu2MSP/peers/peer1.edu2MSP/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/edu2MSP/peers/peer1.edu2MSP/tls:/etc/hyperledger/fabric/tls
        - peer1.edu2MSP:/var/hyperledger/production
    ports:
      - 10051:10051
